/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Gui;

import Beans.Alumno;
import Beans.Curso;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author tracy
 */
public class JFrame1 extends javax.swing.JFrame {

    private List<Alumno> listaAlumnos;

    /**
     * Creates new form JFrame1
     */
    public JFrame1(List<Alumno> listaAlumnos) {
        this.listaAlumnos = listaAlumnos;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jColorChooser1 = new javax.swing.JColorChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtcodAlumno = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        JListCursos = new javax.swing.JList<>();
        btndatos = new javax.swing.JButton();
        txtnomAlumno = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Cursos disponibles ");

        jLabel2.setText("Código alumno");

        jLabel3.setText("Nombre alumno");

        txtcodAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodAlumnoActionPerformed(evt);
            }
        });

        JListCursos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(JListCursos);

        btndatos.setText("Cargar datos");
        btndatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndatosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(btndatos)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(txtcodAlumno)
                    .addComponent(txtnomAlumno, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtcodAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(btndatos))
                        .addGap(18, 18, 18)
                        .addComponent(txtnomAlumno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btndatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndatosActionPerformed
        // Obtener el código del alumno desde el campo de texto
        String codigoAlumno = txtcodAlumno.getText().trim();

        // Lógica para buscar al alumno en la lista de alumnos
        Alumno alumnoEncontrado = null;
        for (Alumno alumno : listaAlumnos) {
            if (alumno.getCodigoAlumno().equals(codigoAlumno)) {
                alumnoEncontrado = alumno;
                break;
            }
        }

        if (alumnoEncontrado != null) {
            // Mostrar el nombre del alumno
            txtnomAlumno.setText(alumnoEncontrado.getNombre());

            // Mostrar los cursos en los que está matriculado en el JList
            DefaultListModel<String> model = new DefaultListModel<>();
            for (Curso curso : alumnoEncontrado.getListaCursos()) {
                model.addElement(curso.getNombreCurso());
            }
            JListCursos.setModel(model);
        } else {
            // Mostrar un mensaje si el alumno no es encontrado
            JOptionPane.showMessageDialog(this, "Alumno no encontrado");
        }
        System.out.println("Código ingresado: " + codigoAlumno);
        for (Alumno alumno : listaAlumnos) {
            System.out.println("Código en lista: " + alumno.getCodigoAlumno());
            if (alumno.getCodigoAlumno().equals(codigoAlumno)) {
                alumnoEncontrado = alumno;
                break;
            }
        }

    }//GEN-LAST:event_btndatosActionPerformed

    private void txtcodAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodAlumnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodAlumnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        List<Alumno> listaAlumnos = new ArrayList<>();

        Alumno alumno1 = new Alumno("70508589", "Tracy", "Huaman", "2310214");
        Alumno alumno2 = new Alumno("70256745", "Lia", "Humareda", "2311135");

        Curso curso1 = new Curso("Mate 1");
        Curso curso2 = new Curso("Mate 2");
        Curso curso3 = new Curso("POO2");
        Curso curso4 = new Curso("Fisica 1");
        Curso curso5 = new Curso("Algebra Lineal");

        // Asignar cursos al alumno
        alumno1.agregarCurso(curso1);
        alumno1.agregarCurso(curso3);
        alumno1.agregarCurso(curso4);
        alumno2.agregarCurso(curso2);
        alumno2.agregarCurso(curso3);
        alumno2.agregarCurso(curso5);

        listaAlumnos.add(alumno1);
        listaAlumnos.add(alumno2);

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new JFrame1(listaAlumnos).setVisible(true);
            }
        }
        );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> JListCursos;
    private javax.swing.JButton btndatos;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtcodAlumno;
    private javax.swing.JTextField txtnomAlumno;
    // End of variables declaration//GEN-END:variables
}
